---
- hosts: all
  become: yes
  tasks:
   - name: Install apache on ubuntu
     apt: name=apache2 state=latest update_cache=yes
     when: ansible_os_family == "Debian"
     tags:
     - install1
   - name: Start apache on ubuntu
     service: name=apache2 state=started enabled=yes
     when: ansible_os_family == "Debian"
   - name: Install httpd on centos
     yum: name=httpd state=latest update_cache=yes
     when: ansible_os_family == "RedHat"
     tags:
     - install2
   - name: Start httpd on Centos
     service: name=httpd state=started enabled=yes
     when: ansible_os_family == "RedHat"
